# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energize_andover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Time', models.CharField(max_length=30)),
                ('Value', models.IntegerField(default=0)),
                ('School', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energize_andover.School')),
            ],
        ),
    ]
